# config/routes.yaml
# the "app_lucky_number" route name is not important yet
app_home:
 path: /
 controller: App\Controller\c_homePage::index

app_partner:
 path: /partenaires
 controller: App\Controller\c_partnerPage::index

app_becomepartner:
 path: /collaborer
 controller: App\Controller\c_becomePartnerPage::index

app_legalnotice:
 path: /mention
 controller: App\Controller\c_legalNoticePage::index

app_about:
 path: /propos
 controller: App\Controller\c_about::index