# config/routes.yaml
# the "app_lucky_number" route name is not important yet
app_home:
 path: /
 controller: App\Controller\c_homePage::index

app_partner:
 path: /partenaires
 controller: App\Controller\c_partnerPage::index