<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIrTJ2kI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIrTJ2kI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIrTJ2kI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIrTJ2kI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIrTJ2kI\App_KernelDevDebugContainer([
    'container.build_hash' => 'IrTJ2kI',
    'container.build_id' => '9d637e4b',
    'container.build_time' => 1676555782,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIrTJ2kI');
