<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW04xTT0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW04xTT0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW04xTT0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW04xTT0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW04xTT0\App_KernelDevDebugContainer([
    'container.build_hash' => 'W04xTT0',
    'container.build_id' => 'e30cf26c',
    'container.build_time' => 1677140605,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW04xTT0');
